# Generated by Django 3.2.6 on 2021-08-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210831_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='locations',
            field=models.ManyToManyField(blank=True, to='main_app.Location'),
        ),
    ]
