# Generated by Django 3.2.6 on 2021-08-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_game_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='locations',
            field=models.ManyToManyField(null=True, to='main_app.Location'),
        ),
    ]
